# tools/patch_manifest_subtitles_v03.py
# Genera captions_v03.srt desde manifest_v03.json.scenes_v03 (determinista)
# NO depende de imports del paquete "studio".

from __future__ import annotations

import json
import argparse
from pathlib import Path
import re


def _ms_to_srt(ts_ms: int) -> str:
    ts_ms = max(0, int(ts_ms))
    hh = ts_ms // 3600000
    ts_ms -= hh * 3600000
    mm = ts_ms // 60000
    ts_ms -= mm * 60000
    ss = ts_ms // 1000
    ms = ts_ms - ss * 1000
    return f"{hh:02d}:{mm:02d}:{ss:02d},{ms:03d}"


def _clean_text(s: str) -> str:
    s = (s or "").strip()
    s = re.sub(r"\s+", " ", s)
    # evita líneas vacías
    if not s:
        s = "..."
    return s


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--pack-dir", required=True)
    ap.add_argument("--out", default="captions_v03.srt")
    ap.add_argument("--max-chars", type=int, default=42)  # para wrap simple
    args = ap.parse_args()

    pack = Path(args.pack_dir)
    manifest_path = pack / "manifest_v03.json"
    if not manifest_path.exists():
        raise SystemExit(f"manifest_v03.json no existe en: {pack}")

    m = json.loads(manifest_path.read_text(encoding="utf-8"))
    scenes = m.get("scenes_v03")
    if not isinstance(scenes, list) or len(scenes) < 1:
        raise SystemExit("manifest no tiene scenes_v03[] válido (corre Scene Builder primero).")

    total_ms = 0
    sb = m.get("scene_builder_v03")
    if isinstance(sb, dict):
        try:
            total_ms = int(sb.get("total_audio_ms") or 0)
        except Exception:
            total_ms = 0

    # construye SRT: 1 bloque por escena
    lines = []
    idx = 1
    prev_end = -1

    for sc in scenes:
        if not isinstance(sc, dict):
            continue

        start = int(sc.get("start_ms") or 0)
        end = int(sc.get("end_ms") or 0)

        # saneo determinista
        if start < 0:
            start = 0
        if end <= start:
            end = start + 250
        if start < prev_end:
            start = prev_end
            if end <= start:
                end = start + 250
        prev_end = end

        text = sc.get("script_text") or sc.get("onscreen") or sc.get("narration") or ""
        text = _clean_text(str(text))

        # wrap simple por ancho (determinista)
        maxc = max(10, int(args.max_chars))
        words = text.split(" ")
        wrapped = []
        cur = ""
        for w in words:
            if not cur:
                cur = w
            elif len(cur) + 1 + len(w) <= maxc:
                cur = cur + " " + w
            else:
                wrapped.append(cur)
                cur = w
        if cur:
            wrapped.append(cur)
        text_out = "\n".join(wrapped[:3])  # máximo 3 líneas

        lines.append(str(idx))
        lines.append(f"{_ms_to_srt(start)} --> {_ms_to_srt(end)}")
        lines.append(text_out)
        lines.append("")  # blank line
        idx += 1

    out_path = pack / args.out
    out_path.write_text("\n".join(lines), encoding="utf-8")

    # anota en manifest (sin romper nada)
    m["captions_v03"] = {
        "srt": str(out_path.name),
        "source": "scenes_v03.script_text",
        "note": "generated by tools/patch_manifest_subtitles_v03.py",
    }
    manifest_path.write_text(json.dumps(m, ensure_ascii=False, indent=2), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
